create or replace noneditionable function DESCUENTO(PRODUCUTO_ID IN NUMBER, FAMILIA_ID IN NUMBER,PORVEEDOR_ID IN NUMBER) return number is
  DESCUENTOS number;
begin
  SELECT SUM(D.DESCUENTO) INTO DESCUENTOS
FROM PV_DESCUENTOS D
WHERE PRODUCUTO_ID = D.PV_PRODUCTOS_ID OR FAMILIA_ID = D.PV_FAMILIA_ID OR PORVEEDOR_ID = D.PV_PROVEEDOR_ID AND D.FECHA_VENCIMIENTO >= SYSDATE;

  return(DESCUENTOS);
end DESCUENTO;
/
