create or replace noneditionable procedure ELIMINAR_DETALLE_INVENTARIO(DETALLE_INVENTARIO_ID_ NUMBER) is
begin
  DELETE FROM PV_DETALLE_INVENTARIO DI
   WHERE DI.DETALLE_INVENTARIO_ID = DETALLE_INVENTARIO_ID_;
end;
/
